version: '3.5'
services:
    todo_app:
        image: nginx:latest
        volumes:
            - .:/usr/share/nginx/html
        networks:
            - default
networks:
    default:
        name: nginx_proxy
        external: true
